services:
  - type: web
    name: controlhub
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "python manage.py create_superuser_if_none && daphne -b 0.0.0.0 -p $PORT controlhub.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@controlhub.com
