# Generated by Django 6.0.4 on 2026-04-30 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('unique_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('operating_system', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('connecting', 'Connecting')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('cpu_info', models.CharField(blank=True, max_length=255)),
                ('ram_total', models.CharField(blank=True, max_length=50)),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
